version: '3.3'
services:
  pihole:
    image: pihole/pihole
    deploy:
      mode: global
      placement:
        constraints: [node.labels.pihole==true]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
     - TZ=Europe/Berlin
     - WEBPASSWORD=
     - WEB_PORT=8000
    volumes:
      - pihole.etc:/etc/pihole/
      - pihole.dnsmasqd:/etc/dnsmasq.d/
    networks:
          - host
networks:
  host:
    external: true

volumes:
    pihole.etc:
    pihole.dnsmasqd:
